# Generated by Django 5.0 on 2023-12-23 23:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_tags_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timePosted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 23, 23, 21, 4, 706900, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
